# KeyHound Enhanced - Google Colab Configuration
# Optimized for Colab environment with GPU acceleration

# Application Settings
app:
  name: "KeyHound Enhanced (Colab)"
  version: "2.0.0"
  debug: false
  log_level: "INFO"
  environment: "colab"

# Bitcoin Cryptography
bitcoin:
  network: "mainnet"
  address_types: ["legacy", "p2sh", "bech32"]
  default_puzzle_bits: 40

# GPU Acceleration (Colab optimized)
gpu:
  enabled: true
  framework: "cuda"
  batch_size: 10000  # Optimized for Colab Pro A100/T4
  max_memory_usage: 0.8  # Use most of available GPU memory

# Performance Settings (Colab optimized)
performance:
  max_threads: 4  # Colab CPU cores
  memory_limit_gb: 12  # Colab RAM limits
  cache_size: 2000
  save_interval_minutes: 30

# Web Interface (Colab tunneling)
web:
  host: "0.0.0.0"
  port: 5000
  debug: false
  secret_key: "colab-secret-key"

# Database (Colab storage)
database:
  type: "sqlite"
  path: "/content/KeyHound/data/keyhound.db"
  backup_interval_hours: 6

# Distributed Computing (Disabled for Colab)
distributed:
  enabled: false  # Single session environment
  master_port: 5555
  worker_timeout: 300
  max_workers: 1

# Security (Relaxed for Colab)
security:
  enable_authentication: false  # Colab sessions are isolated
  session_timeout_minutes: 1440  # 24 hours
  max_login_attempts: 10

# Logging (Colab-friendly)
logging:
  level: "INFO"
  file: "/content/KeyHound/logs/keyhound.log"
  max_size_mb: 100
  backup_count: 2

# Results Storage (Colab + Google Drive)
results:
  directory: "/content/KeyHound/results"
  backup_directory: "/content/drive/MyDrive/KeyHound/results"
  encryption_enabled: false  # Colab sessions are temporary
  compression_enabled: true
  google_drive_sync: true
