# KeyHound Enhanced - Default Configuration
# Enterprise-grade Bitcoin cryptography platform

# Application Settings
app:
  name: "KeyHound Enhanced"
  version: "2.0.0"
  debug: false
  log_level: "INFO"

# Bitcoin Cryptography
bitcoin:
  network: "mainnet"  # mainnet, testnet
  address_types: ["legacy", "p2sh", "bech32"]
  default_puzzle_bits: 40

# GPU Acceleration
gpu:
  enabled: false
  framework: "cuda"  # cuda, opencl, numba
  batch_size: 1000
  max_memory_usage: 0.8  # 80% of available GPU memory

# Performance Settings
performance:
  max_threads: 4
  memory_limit_gb: 8
  cache_size: 1000
  save_interval_minutes: 30

# Web Interface
web:
  host: "0.0.0.0"
  port: 5000
  debug: false
  secret_key: "change-this-in-production"

# Database
database:
  type: "sqlite"  # sqlite, postgresql, mysql
  path: "data/keyhound.db"
  backup_interval_hours: 24

# Distributed Computing
distributed:
  enabled: false
  master_port: 5555
  worker_timeout: 300
  max_workers: 10

# Security
security:
  enable_authentication: false
  session_timeout_minutes: 60
  max_login_attempts: 5

# Logging
logging:
  level: "INFO"
  file: "logs/keyhound.log"
  max_size_mb: 100
  backup_count: 5

# Results Storage
results:
  directory: "results"
  backup_directory: "results/backups"
  encryption_enabled: false
  compression_enabled: true
